### ISSUE TITLE
do you have video or presentation to share? 

### ISSUE THREAD

**Issue by Sandy4321** [passalis/intro_rl_meetup#1]
do you have video or presentation to share?

**Comment by passalis** [comment]
Thanks for your interest! Unfortunately we didn't have any video from the meetup. We will consider this for the following meetups. You can find some slides related to deep RL in [the repository](https://github.com/passalis/intro_rl_meetup/raw/master/presentation.pdf), as well as the slides from the first presentation [here](https://www.dropbox.com/s/jq1ce6787vrkhnb/rl_intro_final_pdf.pdf?dl=0)
